### ISSUE TITLE
Remove arr

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-arrows#5]
@garyb @joneshf What do you think? This could move to `profunctors`, which would make `Arrow` just:

````purescript
class (Category a, Strong a) <= Arrow a
```

**Comment by paf31** [comment]
I'm trying to figure out what I want to change before making a major release ...

**Comment by garyb** [comment]
What would the `arr`-in-profunctors look like?

**Comment by paf31** [comment]
`arr f = rmap f id`

**Comment by garyb** [comment]
Oh ok, cool, yeah :) is there a better/alternative name than `arr` or do you think we just stick with that?

**Comment by paf31** [comment]
Hmm, I guess `arr` is sort of standard, but it's not very good. `pure` would be nice, but it's taken :)
